//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Повышение_квалификации.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SSQL-12R2WEB01.client.parking.ru;Initial Catalog=silverha_vpn06;Persi" +
            "st Security Info=True;User ID=silverha_vpn06;Password=x2eceFMnGf")]
        public string повышение_квалифConnectionString {
            get {
                return ((string)(this["повышение_квалифConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SSQL-12R2WEB01.client.parking.ru;Initial Catalog=silverha_vpn06;Persi" +
            "st Security Info=True;User ID=silverha_vpn06;Password=x2eceFMnGf")]
        public string повышение_квалифConnectionString1 {
            get {
                return ((string)(this["повышение_квалифConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-T251EPD\\SQLEXPRESS;Initial Catalog=Courses;Integrated Securit" +
            "y=True")]
        public string Курсы_ОбученяConnectionString {
            get {
                return ((string)(this["Курсы_ОбученяConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SSQL-12R2WEB01.client.parking.ru;Initial Catalog=silverha_vpn06;Persi" +
            "st Security Info=True;User ID=silverha_vpn06;Password=x2eceFMnGf")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SSQL-12R2WEB01.client.parking.ru;Initial Catalog=silverha_vpn06;Persi" +
            "st Security Info=True;User ID=silverha_vpn06;Password=x2eceFMnGf")]
        public string silverha_fkd6qConnectionString {
            get {
                return ((string)(this["silverha_fkd6qConnectionString"]));
            }
        }
    }
}
